package com.amadeus.xml;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-25T10:50:35.704+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://xml.amadeus.com", name = "AmadeusWebServicesPT")
@XmlSeeAlso({com.amadeus.xml.quqpcq_03_1_1a.ObjectFactory.class, com.amadeus.xml.fsocaq_10_2_1a.ObjectFactory.class, com.amadeus.xml.cltreq_04_1_ia.ObjectFactory.class, com.amadeus.xml.fmpcaq_10_3_1a.ObjectFactory.class, com.amadeus.xml.cltres_04_1_ia.ObjectFactory.class, com.amadeus.xml.fmptbq_10_3_1a.ObjectFactory.class, com.amadeus.xml.quqpcr_03_1_1a.ObjectFactory.class, com.amadeus.xml.tnlres_00_1_1a.ObjectFactory.class, com.amadeus.xml.vlssoq_04_1_1a.ObjectFactory.class, com.amadeus.xml.smpres_97_1_ia.ObjectFactory.class, com.amadeus.xml.smpreq_97_1_ia.ObjectFactory.class, com.amadeus.xml.vlsslq_06_1_1a.ObjectFactory.class, com.amadeus.xml.tipnrr_08_1_1a.ObjectFactory.class, com.amadeus.xml.pnrret_11_1_1a.ObjectFactory.class, com.amadeus.xml.tpcbrr_07_3_1a.ObjectFactory.class, com.amadeus.xml.vlsslr_06_1_1a.ObjectFactory.class, com.amadeus.xml.itares_05_2_ia.ObjectFactory.class, com.amadeus.xml.flireq_97_3_1a.ObjectFactory.class, com.amadeus.xml.tautcr_04_1_1a.ObjectFactory.class, com.amadeus.xml.tipnrq_08_1_1a.ObjectFactory.class, com.amadeus.xml.fsocar_10_2_1a.ObjectFactory.class, com.amadeus.xml.farqnr_07_1_1a.ObjectFactory.class, com.amadeus.xml.hsfres_07_3_1a.ObjectFactory.class, com.amadeus.xml.pnradd_11_1_1a.ObjectFactory.class, com.amadeus.xml.farqnq_07_1_1a.ObjectFactory.class, com.amadeus.xml.hsfreq_07_3_1a.ObjectFactory.class, com.amadeus.xml.itareq_05_2_ia.ObjectFactory.class, com.amadeus.xml.tpcbrq_07_3_1a.ObjectFactory.class, com.amadeus.xml.vlssor_04_1_1a.ObjectFactory.class, com.amadeus.xml.pnrxcl_11_1_1a.ObjectFactory.class, com.amadeus.xml.flires_97_3_1a.ObjectFactory.class, com.amadeus.xml.fmpcar_10_3_1a.ObjectFactory.class, com.amadeus.xml.fmptbr_10_3_1a.ObjectFactory.class, com.amadeus.xml.pnracc_11_1_1a.ObjectFactory.class, com.amadeus.xml.tautcq_04_1_1a.ObjectFactory.class, com.amadeus.xml.ws._2009._01.wbs_session_2_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AmadeusWebServicesPT {

    @WebMethod(operationName = "PNR_AddMultiElements")
    public Response<com.amadeus.xml.pnracc_11_1_1a.PNRReply> pnrAddMultiElementsAsync(
        @WebParam(partName = "PNR_AddMultiElements_11_1", name = "PNR_AddMultiElements", targetNamespace = "http://xml.amadeus.com/PNRADD_11_1_1A")
        com.amadeus.xml.pnradd_11_1_1a.PNRAddMultiElements pnrAddMultiElements111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_AddMultiElements")
    public Future<?> pnrAddMultiElementsAsync(
        @WebParam(partName = "PNR_AddMultiElements_11_1", name = "PNR_AddMultiElements", targetNamespace = "http://xml.amadeus.com/PNRADD_11_1_1A")
        com.amadeus.xml.pnradd_11_1_1a.PNRAddMultiElements pnrAddMultiElements111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.pnracc_11_1_1a.PNRReply> asyncHandler
    );

    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_11_1_1A", partName = "PNR_Reply_11_1")
    @WebMethod(operationName = "PNR_AddMultiElements", action = "http://webservices.amadeus.com/1ASIWPELPEL/PNRADD_11_1_1A")
    public com.amadeus.xml.pnracc_11_1_1a.PNRReply pnrAddMultiElements(
        @WebParam(partName = "PNR_AddMultiElements_11_1", name = "PNR_AddMultiElements", targetNamespace = "http://xml.amadeus.com/PNRADD_11_1_1A")
        com.amadeus.xml.pnradd_11_1_1a.PNRAddMultiElements pnrAddMultiElements111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Retrieve")
    public Response<com.amadeus.xml.pnracc_11_1_1a.PNRReply> pnrRetrieveAsync(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Retrieve")
    public Future<?> pnrRetrieveAsync(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.pnracc_11_1_1a.PNRReply> asyncHandler
    );

    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_11_1_1A", partName = "PNR_Reply_11_1")
    @WebMethod(operationName = "PNR_Retrieve", action = "http://webservices.amadeus.com/1ASIWPELPEL/PNRRET_11_1_1A")
    public com.amadeus.xml.pnracc_11_1_1a.PNRReply pnrRetrieve(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Ticket_CreateTSTFromPricing")
    public Response<com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply> ticketCreateTSTFromPricingAsync(
        @WebParam(partName = "Ticket_CreateTSTFromPricing_4_1", name = "Ticket_CreateTSTFromPricing", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A")
        com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing ticketCreateTSTFromPricing41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Ticket_CreateTSTFromPricing")
    public Future<?> ticketCreateTSTFromPricingAsync(
        @WebParam(partName = "Ticket_CreateTSTFromPricing_4_1", name = "Ticket_CreateTSTFromPricing", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A")
        com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing ticketCreateTSTFromPricing41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply> asyncHandler
    );

    @WebResult(name = "Ticket_CreateTSTFromPricingReply", targetNamespace = "http://xml.amadeus.com/TAUTCR_04_1_1A", partName = "Ticket_CreateTSTFromPricingReply_4_1")
    @WebMethod(operationName = "Ticket_CreateTSTFromPricing", action = "http://webservices.amadeus.com/1ASIWPELPEL/TAUTCQ_04_1_1A")
    public com.amadeus.xml.tautcr_04_1_1a.TicketCreateTSTFromPricingReply ticketCreateTSTFromPricing(
        @WebParam(partName = "Ticket_CreateTSTFromPricing_4_1", name = "Ticket_CreateTSTFromPricing", targetNamespace = "http://xml.amadeus.com/TAUTCQ_04_1_1A")
        com.amadeus.xml.tautcq_04_1_1a.TicketCreateTSTFromPricing ticketCreateTSTFromPricing41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_CheckRules")
    public Response<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply> fareCheckRulesAsync(
        @WebParam(partName = "Fare_CheckRules_7_1", name = "Fare_CheckRules", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules fareCheckRules71,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_CheckRules")
    public Future<?> fareCheckRulesAsync(
        @WebParam(partName = "Fare_CheckRules_7_1", name = "Fare_CheckRules", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules fareCheckRules71,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply> asyncHandler
    );

    @WebResult(name = "Fare_CheckRulesReply", targetNamespace = "http://xml.amadeus.com/FARQNR_07_1_1A", partName = "Fare_CheckRulesReply_7_1")
    @WebMethod(operationName = "Fare_CheckRules", action = "http://webservices.amadeus.com/1ASIWPELPEL/FARQNQ_07_1_1A")
    public com.amadeus.xml.farqnr_07_1_1a.FareCheckRulesReply fareCheckRules(
        @WebParam(partName = "Fare_CheckRules_7_1", name = "Fare_CheckRules", targetNamespace = "http://xml.amadeus.com/FARQNQ_07_1_1A")
        com.amadeus.xml.farqnq_07_1_1a.FareCheckRules fareCheckRules71,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_RetrieveSeatMap")
    public Response<com.amadeus.xml.smpres_97_1_ia.AirRetrieveSeatMapReply> airRetrieveSeatMapAsync(
        @WebParam(partName = "Air_RetrieveSeatMap_97_1", name = "Air_RetrieveSeatMap", targetNamespace = "http://xml.amadeus.com/SMPREQ_97_1_IA")
        com.amadeus.xml.smpreq_97_1_ia.AirRetrieveSeatMap airRetrieveSeatMap971,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_RetrieveSeatMap")
    public Future<?> airRetrieveSeatMapAsync(
        @WebParam(partName = "Air_RetrieveSeatMap_97_1", name = "Air_RetrieveSeatMap", targetNamespace = "http://xml.amadeus.com/SMPREQ_97_1_IA")
        com.amadeus.xml.smpreq_97_1_ia.AirRetrieveSeatMap airRetrieveSeatMap971,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.smpres_97_1_ia.AirRetrieveSeatMapReply> asyncHandler
    );

    @WebResult(name = "Air_RetrieveSeatMapReply", targetNamespace = "http://xml.amadeus.com/SMPRES_97_1_IA", partName = "Air_RetrieveSeatMapReply_97_1")
    @WebMethod(operationName = "Air_RetrieveSeatMap", action = "http://webservices.amadeus.com/1ASIWPELPEL/SMPREQ_97_1_IA")
    public com.amadeus.xml.smpres_97_1_ia.AirRetrieveSeatMapReply airRetrieveSeatMap(
        @WebParam(partName = "Air_RetrieveSeatMap_97_1", name = "Air_RetrieveSeatMap", targetNamespace = "http://xml.amadeus.com/SMPREQ_97_1_IA")
        com.amadeus.xml.smpreq_97_1_ia.AirRetrieveSeatMap airRetrieveSeatMap971,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_InformativePricingWithoutPNR")
    public Response<com.amadeus.xml.tipnrr_08_1_1a.FareInformativePricingWithoutPNRReply> fareInformativePricingWithoutPNRAsync(
        @WebParam(partName = "Fare_InformativePricingWithoutPNR_8_1", name = "Fare_InformativePricingWithoutPNR", targetNamespace = "http://xml.amadeus.com/TIPNRQ_08_1_1A")
        com.amadeus.xml.tipnrq_08_1_1a.FareInformativePricingWithoutPNR fareInformativePricingWithoutPNR81,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_InformativePricingWithoutPNR")
    public Future<?> fareInformativePricingWithoutPNRAsync(
        @WebParam(partName = "Fare_InformativePricingWithoutPNR_8_1", name = "Fare_InformativePricingWithoutPNR", targetNamespace = "http://xml.amadeus.com/TIPNRQ_08_1_1A")
        com.amadeus.xml.tipnrq_08_1_1a.FareInformativePricingWithoutPNR fareInformativePricingWithoutPNR81,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.tipnrr_08_1_1a.FareInformativePricingWithoutPNRReply> asyncHandler
    );

    @WebResult(name = "Fare_InformativePricingWithoutPNRReply", targetNamespace = "http://xml.amadeus.com/TIPNRR_08_1_1A", partName = "Fare_InformativePricingWithoutPNRReply_8_1")
    @WebMethod(operationName = "Fare_InformativePricingWithoutPNR", action = "http://webservices.amadeus.com/1ASIWPELPEL/TIPNRQ_08_1_1A")
    public com.amadeus.xml.tipnrr_08_1_1a.FareInformativePricingWithoutPNRReply fareInformativePricingWithoutPNR(
        @WebParam(partName = "Fare_InformativePricingWithoutPNR_8_1", name = "Fare_InformativePricingWithoutPNR", targetNamespace = "http://xml.amadeus.com/TIPNRQ_08_1_1A")
        com.amadeus.xml.tipnrq_08_1_1a.FareInformativePricingWithoutPNR fareInformativePricingWithoutPNR81,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Retrieve2")
    public Response<com.amadeus.xml.tnlres_00_1_1a.PNRList> pnrRetrieve2Async(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Retrieve2")
    public Future<?> pnrRetrieve2Async(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.tnlres_00_1_1a.PNRList> asyncHandler
    );

    @WebResult(name = "PNR_List", targetNamespace = "http://xml.amadeus.com/TNLRES_00_1_1A", partName = "PNR_List_0_1")
    @WebMethod(operationName = "PNR_Retrieve2", action = "http://webservices.amadeus.com/1ASIWPELPEL/PNRRET_11_1_1A")
    public com.amadeus.xml.tnlres_00_1_1a.PNRList pnrRetrieve2(
        @WebParam(partName = "PNR_Retrieve_11_1", name = "PNR_Retrieve", targetNamespace = "http://xml.amadeus.com/PNRRET_11_1_1A")
        com.amadeus.xml.pnrret_11_1_1a.PNRRetrieve pnrRetrieve111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Queue_PlacePNR")
    public Response<com.amadeus.xml.quqpcr_03_1_1a.QueuePlacePNRReply> queuePlacePNRAsync(
        @WebParam(partName = "Queue_PlacePNR_3_1", name = "Queue_PlacePNR", targetNamespace = "http://xml.amadeus.com/QUQPCQ_03_1_1A")
        com.amadeus.xml.quqpcq_03_1_1a.QueuePlacePNR queuePlacePNR31,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Queue_PlacePNR")
    public Future<?> queuePlacePNRAsync(
        @WebParam(partName = "Queue_PlacePNR_3_1", name = "Queue_PlacePNR", targetNamespace = "http://xml.amadeus.com/QUQPCQ_03_1_1A")
        com.amadeus.xml.quqpcq_03_1_1a.QueuePlacePNR queuePlacePNR31,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.quqpcr_03_1_1a.QueuePlacePNRReply> asyncHandler
    );

    @WebResult(name = "Queue_PlacePNRReply", targetNamespace = "http://xml.amadeus.com/QUQPCR_03_1_1A", partName = "Queue_PlacePNRReply_3_1")
    @WebMethod(operationName = "Queue_PlacePNR", action = "http://webservices.amadeus.com/1ASIWPELPEL/QUQPCQ_03_1_1A")
    public com.amadeus.xml.quqpcr_03_1_1a.QueuePlacePNRReply queuePlacePNR(
        @WebParam(partName = "Queue_PlacePNR_3_1", name = "Queue_PlacePNR", targetNamespace = "http://xml.amadeus.com/QUQPCQ_03_1_1A")
        com.amadeus.xml.quqpcq_03_1_1a.QueuePlacePNR queuePlacePNR31,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_FlightInfo")
    public Response<com.amadeus.xml.flires_97_3_1a.AirFlightInfoReply> airFlightInfoAsync(
        @WebParam(partName = "Air_FlightInfo_97_3", name = "Air_FlightInfo", targetNamespace = "http://xml.amadeus.com/FLIREQ_97_3_1A")
        com.amadeus.xml.flireq_97_3_1a.AirFlightInfo airFlightInfo973,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_FlightInfo")
    public Future<?> airFlightInfoAsync(
        @WebParam(partName = "Air_FlightInfo_97_3", name = "Air_FlightInfo", targetNamespace = "http://xml.amadeus.com/FLIREQ_97_3_1A")
        com.amadeus.xml.flireq_97_3_1a.AirFlightInfo airFlightInfo973,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.flires_97_3_1a.AirFlightInfoReply> asyncHandler
    );

    @WebResult(name = "Air_FlightInfoReply", targetNamespace = "http://xml.amadeus.com/FLIRES_97_3_1A", partName = "Air_FlightInfoReply_97_3")
    @WebMethod(operationName = "Air_FlightInfo", action = "http://webservices.amadeus.com/1ASIWPELPEL/FLIREQ_97_3_1A")
    public com.amadeus.xml.flires_97_3_1a.AirFlightInfoReply airFlightInfo(
        @WebParam(partName = "Air_FlightInfo_97_3", name = "Air_FlightInfo", targetNamespace = "http://xml.amadeus.com/FLIREQ_97_3_1A")
        com.amadeus.xml.flireq_97_3_1a.AirFlightInfo airFlightInfo973,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_PricePNRWithBookingClass")
    public Response<com.amadeus.xml.tpcbrr_07_3_1a.FarePricePNRWithBookingClassReply> farePricePNRWithBookingClassAsync(
        @WebParam(partName = "Fare_PricePNRWithBookingClass_7_3", name = "Fare_PricePNRWithBookingClass", targetNamespace = "http://xml.amadeus.com/TPCBRQ_07_3_1A")
        com.amadeus.xml.tpcbrq_07_3_1a.FarePricePNRWithBookingClass farePricePNRWithBookingClass73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_PricePNRWithBookingClass")
    public Future<?> farePricePNRWithBookingClassAsync(
        @WebParam(partName = "Fare_PricePNRWithBookingClass_7_3", name = "Fare_PricePNRWithBookingClass", targetNamespace = "http://xml.amadeus.com/TPCBRQ_07_3_1A")
        com.amadeus.xml.tpcbrq_07_3_1a.FarePricePNRWithBookingClass farePricePNRWithBookingClass73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.tpcbrr_07_3_1a.FarePricePNRWithBookingClassReply> asyncHandler
    );

    @WebResult(name = "Fare_PricePNRWithBookingClassReply", targetNamespace = "http://xml.amadeus.com/TPCBRR_07_3_1A", partName = "Fare_PricePNRWithBookingClassReply_7_3")
    @WebMethod(operationName = "Fare_PricePNRWithBookingClass", action = "http://webservices.amadeus.com/1ASIWPELPEL/TPCBRQ_07_3_1A")
    public com.amadeus.xml.tpcbrr_07_3_1a.FarePricePNRWithBookingClassReply farePricePNRWithBookingClass(
        @WebParam(partName = "Fare_PricePNRWithBookingClass_7_3", name = "Fare_PricePNRWithBookingClass", targetNamespace = "http://xml.amadeus.com/TPCBRQ_07_3_1A")
        com.amadeus.xml.tpcbrq_07_3_1a.FarePricePNRWithBookingClass farePricePNRWithBookingClass73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Cancel")
    public Response<com.amadeus.xml.pnracc_11_1_1a.PNRReply> pnrCancelAsync(
        @WebParam(partName = "PNR_Cancel_11_1", name = "PNR_Cancel", targetNamespace = "http://xml.amadeus.com/PNRXCL_11_1_1A")
        com.amadeus.xml.pnrxcl_11_1_1a.PNRCancel pnrCancel111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Cancel")
    public Future<?> pnrCancelAsync(
        @WebParam(partName = "PNR_Cancel_11_1", name = "PNR_Cancel", targetNamespace = "http://xml.amadeus.com/PNRXCL_11_1_1A")
        com.amadeus.xml.pnrxcl_11_1_1a.PNRCancel pnrCancel111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.pnracc_11_1_1a.PNRReply> asyncHandler
    );

    @WebResult(name = "PNR_Reply", targetNamespace = "http://xml.amadeus.com/PNRACC_11_1_1A", partName = "PNR_Reply_11_1")
    @WebMethod(operationName = "PNR_Cancel", action = "http://webservices.amadeus.com/1ASIWPELPEL/PNRXCL_11_1_1A")
    public com.amadeus.xml.pnracc_11_1_1a.PNRReply pnrCancel(
        @WebParam(partName = "PNR_Cancel_11_1", name = "PNR_Cancel", targetNamespace = "http://xml.amadeus.com/PNRXCL_11_1_1A")
        com.amadeus.xml.pnrxcl_11_1_1a.PNRCancel pnrCancel111,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_SellByFareCalendar")
    public Response<com.amadeus.xml.fsocar_10_2_1a.FareSellByFareCalendarReply> fareSellByFareCalendarAsync(
        @WebParam(partName = "Fare_SellByFareCalendar_10_2", name = "Fare_SellByFareCalendar", targetNamespace = "http://xml.amadeus.com/FSOCAQ_10_2_1A")
        com.amadeus.xml.fsocaq_10_2_1a.FareSellByFareCalendar fareSellByFareCalendar102,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_SellByFareCalendar")
    public Future<?> fareSellByFareCalendarAsync(
        @WebParam(partName = "Fare_SellByFareCalendar_10_2", name = "Fare_SellByFareCalendar", targetNamespace = "http://xml.amadeus.com/FSOCAQ_10_2_1A")
        com.amadeus.xml.fsocaq_10_2_1a.FareSellByFareCalendar fareSellByFareCalendar102,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.fsocar_10_2_1a.FareSellByFareCalendarReply> asyncHandler
    );

    @WebResult(name = "Fare_SellByFareCalendarReply", targetNamespace = "http://xml.amadeus.com/FSOCAR_10_2_1A", partName = "Fare_SellByFareCalendarReply_10_2")
    @WebMethod(operationName = "Fare_SellByFareCalendar", action = "http://webservices.amadeus.com/1ASIWPELPEL/FSOCAQ_10_2_1A")
    public com.amadeus.xml.fsocar_10_2_1a.FareSellByFareCalendarReply fareSellByFareCalendar(
        @WebParam(partName = "Fare_SellByFareCalendar_10_2", name = "Fare_SellByFareCalendar", targetNamespace = "http://xml.amadeus.com/FSOCAQ_10_2_1A")
        com.amadeus.xml.fsocaq_10_2_1a.FareSellByFareCalendar fareSellByFareCalendar102,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_MasterPricerTravelBoardSearch")
    public Response<com.amadeus.xml.fmptbr_10_3_1a.FareMasterPricerTravelBoardSearchReply> fareMasterPricerTravelBoardSearchAsync(
        @WebParam(partName = "Fare_MasterPricerTravelBoardSearch_10_3", name = "Fare_MasterPricerTravelBoardSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_10_3_1A")
        com.amadeus.xml.fmptbq_10_3_1a.FareMasterPricerTravelBoardSearch fareMasterPricerTravelBoardSearch103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_MasterPricerTravelBoardSearch")
    public Future<?> fareMasterPricerTravelBoardSearchAsync(
        @WebParam(partName = "Fare_MasterPricerTravelBoardSearch_10_3", name = "Fare_MasterPricerTravelBoardSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_10_3_1A")
        com.amadeus.xml.fmptbq_10_3_1a.FareMasterPricerTravelBoardSearch fareMasterPricerTravelBoardSearch103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.fmptbr_10_3_1a.FareMasterPricerTravelBoardSearchReply> asyncHandler
    );

    @WebResult(name = "Fare_MasterPricerTravelBoardSearchReply", targetNamespace = "http://xml.amadeus.com/FMPTBR_10_3_1A", partName = "Fare_MasterPricerTravelBoardSearchReply_10_3")
    @WebMethod(operationName = "Fare_MasterPricerTravelBoardSearch", action = "http://webservices.amadeus.com/1ASIWPELPEL/FMPTBQ_10_3_1A")
    public com.amadeus.xml.fmptbr_10_3_1a.FareMasterPricerTravelBoardSearchReply fareMasterPricerTravelBoardSearch(
        @WebParam(partName = "Fare_MasterPricerTravelBoardSearch_10_3", name = "Fare_MasterPricerTravelBoardSearch", targetNamespace = "http://xml.amadeus.com/FMPTBQ_10_3_1A")
        com.amadeus.xml.fmptbq_10_3_1a.FareMasterPricerTravelBoardSearch fareMasterPricerTravelBoardSearch103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Security_Authenticate")
    public Response<com.amadeus.xml.vlsslr_06_1_1a.SecurityAuthenticateReply> securityAuthenticateAsync(
        @WebParam(partName = "Security_Authenticate_6_1", name = "Security_Authenticate", targetNamespace = "http://xml.amadeus.com/VLSSLQ_06_1_1A")
        com.amadeus.xml.vlsslq_06_1_1a.SecurityAuthenticate securityAuthenticate61,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Security_Authenticate")
    public Future<?> securityAuthenticateAsync(
        @WebParam(partName = "Security_Authenticate_6_1", name = "Security_Authenticate", targetNamespace = "http://xml.amadeus.com/VLSSLQ_06_1_1A")
        com.amadeus.xml.vlsslq_06_1_1a.SecurityAuthenticate securityAuthenticate61,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.vlsslr_06_1_1a.SecurityAuthenticateReply> asyncHandler
    );

    @WebResult(name = "Security_AuthenticateReply", targetNamespace = "http://xml.amadeus.com/VLSSLR_06_1_1A", partName = "Security_AuthenticateReply_6_1")
    @WebMethod(operationName = "Security_Authenticate", action = "http://webservices.amadeus.com/1ASIWPELPEL/VLSSLQ_06_1_1A")
    public com.amadeus.xml.vlsslr_06_1_1a.SecurityAuthenticateReply securityAuthenticate(
        @WebParam(partName = "Security_Authenticate_6_1", name = "Security_Authenticate", targetNamespace = "http://xml.amadeus.com/VLSSLQ_06_1_1A")
        com.amadeus.xml.vlsslq_06_1_1a.SecurityAuthenticate securityAuthenticate61,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Command_Cryptic")
    public Response<com.amadeus.xml.hsfres_07_3_1a.CommandCrypticReply> commandCrypticAsync(
        @WebParam(partName = "Command_Cryptic_7_3", name = "Command_Cryptic", targetNamespace = "http://xml.amadeus.com/HSFREQ_07_3_1A")
        com.amadeus.xml.hsfreq_07_3_1a.CommandCryptic commandCryptic73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Command_Cryptic")
    public Future<?> commandCrypticAsync(
        @WebParam(partName = "Command_Cryptic_7_3", name = "Command_Cryptic", targetNamespace = "http://xml.amadeus.com/HSFREQ_07_3_1A")
        com.amadeus.xml.hsfreq_07_3_1a.CommandCryptic commandCryptic73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.hsfres_07_3_1a.CommandCrypticReply> asyncHandler
    );

    @WebResult(name = "Command_CrypticReply", targetNamespace = "http://xml.amadeus.com/HSFRES_07_3_1A", partName = "Command_CrypticReply_7_3")
    @WebMethod(operationName = "Command_Cryptic", action = "http://webservices.amadeus.com/1ASIWPELPEL/HSFREQ_07_3_1A")
    public com.amadeus.xml.hsfres_07_3_1a.CommandCrypticReply commandCryptic(
        @WebParam(partName = "Command_Cryptic_7_3", name = "Command_Cryptic", targetNamespace = "http://xml.amadeus.com/HSFREQ_07_3_1A")
        com.amadeus.xml.hsfreq_07_3_1a.CommandCryptic commandCryptic73,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_SellFromRecommendation")
    public Response<com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply> airSellFromRecommendationAsync(
        @WebParam(partName = "Air_SellFromRecommendation_5_2", name = "Air_SellFromRecommendation", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation airSellFromRecommendation52,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Air_SellFromRecommendation")
    public Future<?> airSellFromRecommendationAsync(
        @WebParam(partName = "Air_SellFromRecommendation_5_2", name = "Air_SellFromRecommendation", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation airSellFromRecommendation52,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply> asyncHandler
    );

    @WebResult(name = "Air_SellFromRecommendationReply", targetNamespace = "http://xml.amadeus.com/ITARES_05_2_IA", partName = "Air_SellFromRecommendationReply_5_2")
    @WebMethod(operationName = "Air_SellFromRecommendation", action = "http://webservices.amadeus.com/1ASIWPELPEL/ITAREQ_05_2_IA")
    public com.amadeus.xml.itares_05_2_ia.AirSellFromRecommendationReply airSellFromRecommendation(
        @WebParam(partName = "Air_SellFromRecommendation_5_2", name = "Air_SellFromRecommendation", targetNamespace = "http://xml.amadeus.com/ITAREQ_05_2_IA")
        com.amadeus.xml.itareq_05_2_ia.AirSellFromRecommendation airSellFromRecommendation52,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_MasterPricerCalendar")
    public Response<com.amadeus.xml.fmpcar_10_3_1a.FareMasterPricerCalendarReply> fareMasterPricerCalendarAsync(
        @WebParam(partName = "Fare_MasterPricerCalendar_10_3", name = "Fare_MasterPricerCalendar", targetNamespace = "http://xml.amadeus.com/FMPCAQ_10_3_1A")
        com.amadeus.xml.fmpcaq_10_3_1a.FareMasterPricerCalendar fareMasterPricerCalendar103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Fare_MasterPricerCalendar")
    public Future<?> fareMasterPricerCalendarAsync(
        @WebParam(partName = "Fare_MasterPricerCalendar_10_3", name = "Fare_MasterPricerCalendar", targetNamespace = "http://xml.amadeus.com/FMPCAQ_10_3_1A")
        com.amadeus.xml.fmpcaq_10_3_1a.FareMasterPricerCalendar fareMasterPricerCalendar103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.fmpcar_10_3_1a.FareMasterPricerCalendarReply> asyncHandler
    );

    @WebResult(name = "Fare_MasterPricerCalendarReply", targetNamespace = "http://xml.amadeus.com/FMPCAR_10_3_1A", partName = "Fare_MasterPricerCalendarReply_10_3")
    @WebMethod(operationName = "Fare_MasterPricerCalendar", action = "http://webservices.amadeus.com/1ASIWPELPEL/FMPCAQ_10_3_1A")
    public com.amadeus.xml.fmpcar_10_3_1a.FareMasterPricerCalendarReply fareMasterPricerCalendar(
        @WebParam(partName = "Fare_MasterPricerCalendar_10_3", name = "Fare_MasterPricerCalendar", targetNamespace = "http://xml.amadeus.com/FMPCAQ_10_3_1A")
        com.amadeus.xml.fmpcaq_10_3_1a.FareMasterPricerCalendar fareMasterPricerCalendar103,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Security_SignOut")
    public Response<com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply> securitySignOutAsync(
        @WebParam(partName = "Security_SignOut_4_1", name = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A")
        com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut securitySignOut41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "Security_SignOut")
    public Future<?> securitySignOutAsync(
        @WebParam(partName = "Security_SignOut_4_1", name = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A")
        com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut securitySignOut41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply> asyncHandler
    );

    @WebResult(name = "Security_SignOutReply", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", partName = "Security_SignOutReply_4_1")
    @WebMethod(operationName = "Security_SignOut", action = "http://webservices.amadeus.com/1ASIWPELPEL/VLSSOQ_04_1_1A")
    public com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply securitySignOut(
        @WebParam(partName = "Security_SignOut_4_1", name = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A")
        com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut securitySignOut41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Ignore")
    public Response<com.amadeus.xml.cltres_04_1_ia.PNRIgnoreReply> pnrIgnoreAsync(
        @WebParam(partName = "PNR_Ignore_4_1", name = "PNR_Ignore", targetNamespace = "http://xml.amadeus.com/CLTREQ_04_1_IA")
        com.amadeus.xml.cltreq_04_1_ia.PNRIgnore pnrIgnore41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );

    @WebMethod(operationName = "PNR_Ignore")
    public Future<?> pnrIgnoreAsync(
        @WebParam(partName = "PNR_Ignore_4_1", name = "PNR_Ignore", targetNamespace = "http://xml.amadeus.com/CLTREQ_04_1_IA")
        com.amadeus.xml.cltreq_04_1_ia.PNRIgnore pnrIgnore41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.amadeus.xml.cltres_04_1_ia.PNRIgnoreReply> asyncHandler
    );

    @WebResult(name = "PNR_IgnoreReply", targetNamespace = "http://xml.amadeus.com/CLTRES_04_1_IA", partName = "PNR_IgnoreReply_4_1")
    @WebMethod(operationName = "PNR_Ignore", action = "http://webservices.amadeus.com/1ASIWPELPEL/CLTREQ_04_1_IA")
    public com.amadeus.xml.cltres_04_1_ia.PNRIgnoreReply pnrIgnore(
        @WebParam(partName = "PNR_Ignore_4_1", name = "PNR_Ignore", targetNamespace = "http://xml.amadeus.com/CLTREQ_04_1_IA")
        com.amadeus.xml.cltreq_04_1_ia.PNRIgnore pnrIgnore41,
        @WebParam(partName = "Session", mode = WebParam.Mode.INOUT, name = "Session", targetNamespace = "http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd", header = true)
        javax.xml.ws.Holder<com.amadeus.xml.ws._2009._01.wbs_session_2_0.Session> session
    );
}
