package com.amadeus.xml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-25T10:50:35.771+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "AmadeusWebServices", 
                  wsdlLocation = "file:/home/michal/NetBeansProjects/test1/src/wsdl/AmadeusWebServices.wsdl",
                  targetNamespace = "http://xml.amadeus.com") 
public class AmadeusWebServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xml.amadeus.com", "AmadeusWebServices");
    public final static QName AmadeusWebServicesPort = new QName("http://xml.amadeus.com", "AmadeusWebServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/michal/NetBeansProjects/test1/src/wsdl/AmadeusWebServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AmadeusWebServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/michal/NetBeansProjects/test1/src/wsdl/AmadeusWebServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AmadeusWebServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AmadeusWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AmadeusWebServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AmadeusWebServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AmadeusWebServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AmadeusWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AmadeusWebServicesPT
     */
    @WebEndpoint(name = "AmadeusWebServicesPort")
    public AmadeusWebServicesPT getAmadeusWebServicesPort() {
        return super.getPort(AmadeusWebServicesPort, AmadeusWebServicesPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmadeusWebServicesPT
     */
    @WebEndpoint(name = "AmadeusWebServicesPort")
    public AmadeusWebServicesPT getAmadeusWebServicesPort(WebServiceFeature... features) {
        return super.getPort(AmadeusWebServicesPort, AmadeusWebServicesPT.class, features);
    }

}
